### ISSUE TITLE
重新连接后正在阅读的章节字体加载不正确

### ISSUE THREAD

**Issue by twtan** [LightNovelShelf/Web#103]
![Screenshot_2022-03-14-22-05-35-704_com microsoft](https://user-images.githubusercontent.com/79256225/158189094-2c852957-482e-4ae1-a17f-292c49506c3c.jpg)
MIUI使用EDGE浏览器切换到到后台后一段时间再切回来会乱码
要返回小说目录然后关闭浏览器再启动浏览器打开章节才可以
或者清除一次缓存

**Comment by wuyu8512** [comment]
这是设计上的缺点，所有人都有这个问题，只需要刷新或者来回切换章节即可解决

**Comment by wuyu8512** [comment]
已解决
