### ISSUE TITLE
访问困难

### ISSUE THREAD

**Issue by rinnelin** [LightNovelShelf/Web#106]
pc上点击登录是Failed to fetch  印象中还有换个环境什么的提示文不过是前几天所以具体不太清楚了 结果当初是手机注册成功和阅览
手机昨天今天看的好好的  刚刚点下一章就说没连上什么的  然后各种不行退出想着重新登录干脆也不行了  要么是全局下“发生了ssl错误,无法建立与该服务器的连接” 要么直连下是“无法连接服务器” 要么选择配置规则时候是“kCFErrorDomainCFNetwork310”
平时有在使用v，日本结点

**Comment by wuyu8512** [comment]
正在维护

**Comment by rinnelin** [comment]
呃  就算是维护 那为什么pc我总是用不了呢？
