### ISSUE TITLE
登陆不了，提示操作异常

### ISSUE THREAD

**Issue by sakuyazh** [LightNovelShelf/Web#117]
登陆的时候提示操作异常，请更换环境重新尝试

估计是google的captcha没弹出来， 翻不翻墙都不行

**Comment by wuyu8512** [comment]
是rcaptcha判断你是机器人，并不是弹不出来

**Comment by sakuyazh** [comment]
> 是rcaptcha判断你是机器人，并不是弹不出来

reCAPTCHA判断完正常不是都会弹个校验出来的嘛， 我这从来没见过就没了

**Comment by wuyu8512** [comment]
> 

v3版本全后台，无需点击图片验证码

**Comment by sakuyazh** [comment]
> > 
> 
> v3版本全后台，无需点击图片验证码

了解了， 我换其他浏览器试试，感谢
