### ISSUE TITLE
页面居中遭破坏

### ISSUE THREAD

**Issue by baka-gourd** [LightNovelShelf/Web#126]
https://github.com/LightNovelShelf/Web/commit/ae38b5f59a7aff615037d482a157b6b21b770901
margin需要重新定义，不然
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/36119339/171024634-0e530b98-b3b4-45f0-8b36-009498d005b8.png">

**Comment by wuyu8512** [comment]
你的这个页面有点奇怪啊，设置页是撑满宽度的啊

**Comment by baka-gourd** [comment]
> 你的这个页面有点奇怪啊，设置页是撑满宽度的啊

啊你看看设置，之前就加了可调宽

**Comment by wuyu8512** [comment]
> 啊你看看设置，之前就加了可调宽

可是那是阅读页面的可调宽啊，和设置无关

**Comment by baka-gourd** [comment]
![Screenshot_20220531_122800_com.microsoft.emmx.png](https://user-images.githubusercontent.com/36119339/171092861-30511e2c-b996-4b48-9ee7-4f01ee25f4ef.png)

**Comment by wuyu8512** [comment]
肯定不是我写的，不如说我觉得这东西，压根就没意义
