### ISSUE TITLE
Read页面 字体设置以及阅读背景

### ISSUE THREAD

**Issue by wuyu8512** [LightNovelShelf/Web#15]
新增Setting路由，顶部放置选项卡(目前只需要阅读选项卡)，在选项中设置阅读部分的字体大小和阅读背景，并应用到阅读页面
阅读背景的几张图片参考旧版，要求有 不设置，纸质(黑暗和明亮模式不同)，纯色 三种类型

**Comment by Azuki-Azusa** [comment]
已合并
