### ISSUE TITLE
【feat】我的书架模块

### ISSUE THREAD

**Issue by Inori-Lover** [LightNovelShelf/Web#17]
目标：
1. 一个用来记录书架数据的store（pinia）
2. 一个用来记录书架数据的db（indexDB）
3. 对外提供“加入书架”按钮，按钮入参为bookID，无须任何多余回调、定义，引入即可用
4. 书架页面滚动加载or分页加载
5. 书架数据增量记录，免除大量序列化操作

**Comment by wuyu8512** [comment]
滚动吧

**Comment by Inori-Lover** [comment]
> 个人倾向于滚动

在做的时候也其实考虑到分页之后没法做排序的问题，最后可能还是会做成滚动。
还在想吧

**Comment by Inori-Lover** [comment]
> 目标：
> 
> 1. 一个用来记录书架数据的store（pinia）
> 2. 一个用来记录书架数据的db（indexDB）
> 3. 对外提供“加入书架”按钮，按钮入参为bookID，无须任何多余回调、定义，引入即可用
> 4. 书架页面滚动加载or分页加载
> 5. 书架数据增量记录，免除大量序列化操作


列表有两个模式，管理模式&阅读模式；
阅读模式下卡片点击进入详情，不可拖拽；分组点击为切换路由，进入分组详情
管理模式下卡片点击为多选切换，短时按住后可拖拽；分组点击为modal预览，分组暂不考虑嵌套，分组内拖拽到蒙层为移出分组；短时按住同样是拖拽
拖拽时手指位于图标中间时触发效果为新建分组或添加至分组；过半后未调换位置（这个阈值可以调整）

PC模式下通过接管右键菜单进入管理模式，拖拽不需要短时按住，直接就可以拖

**Comment by wuyu8512** [comment]
重新开了，记录后续优化情况

**Comment by wuyu8512** [comment]
我把入口关掉了，发现一个严重的问题
目前观察到的情况是，从除了书架以外的页面进入网站，再进入书架页面
如果是有文件夹的情况，则每有一个文件夹就会多一次请求(以及后续的GetBookList)
