### ISSUE TITLE
你好，请教您一点问题可以吗？

### ISSUE THREAD

**Issue by Atlantis829** [LightNovelShelf/Web#175]

**Comment by Atlantis829** [comment]
> 我以前看到您参与过一个软件的讨论，现在我遇到了一个问题需要解决，我不知道私信在哪，只能用这种方式，不知道您可不可以为我解答一下关于windivert的编译问题

**Comment by wuyu8512** [comment]
当然是有现成的不用自己编译，官方repo release里面有
