### ISSUE TITLE
【feat】登录模块

### ISSUE THREAD

**Issue by Inori-Lover** [LightNovelShelf/Web#18]
目标（P0）：
1. 完成登录流程
2. 登陆后long-time token的储存
3. short-time token的换取、ws链接的授权使用

待定（P1）：
1. 用户密码提交是否先hash/encode/encrypt（以及如果要，应该用哪个算法，是否考虑优先使用浏览器内置的手段）

**Comment by wuyu8512** [comment]
本周日合并
