### ISSUE TITLE
建议PC界面也添加自动隐藏顶栏，并增加手动显示或隐藏顶栏选项

### ISSUE THREAD

**Issue by xyhxh46** [LightNovelShelf/Web#196]
手机端是可以自动隐藏的，但是PC端不行，所以建议添加此功能，此外，一向上滑动顶栏又会出现遮住视野，比较影响沉浸感，因为我有时看漏了一两句想往上滑一下，刚好这个时候顶栏就出来遮住了，就很别扭，所以能否在按钮那里多加一个选项来切换是否显示顶栏，相信这样阅读体验会好很多（起点这方面做的就很不错，阅读的时候始终不会显示顶栏）

**Comment by wuyu8512** [comment]
很可惜这些都是经过考虑后刻意这么做的
这些功能都很简单，我建议是尝试自己修改

**Comment by xyhxh46** [comment]
> 很可惜这些都是经过考虑后刻意这么做的
> 这些功能都很简单，我建议是尝试自己修改

原来是刻意做的，我说怎么这么反直觉，不过如果是这样，我就算提交 Pr 也合并不了吧

**Comment by wuyu8512** [comment]
改一个自用啊

**Comment by xyhxh46** [comment]
> 改一个自用啊

行吧，谢谢你的回复
