### ISSUE TITLE
同名或同糸列书籍推荐显示

### ISSUE THREAD

**Issue by Rainsan86** [LightNovelShelf/Web#197]
可以做同名或同糸列书籍推荐显示，点击在同名或同糸列书籍某一本(每一本都可以)在目录下方会显显示同一个系列的书(省去搜索的麻烦)。然后这个功能可以在设置里开关

(仅建议)

**Comment by wuyu8512** [comment]
应该是不会做，自己维护一下“我的书架”里的文件夹吧
