### ISSUE TITLE
有新內容可以用了，請刷新或重新打開網頁的iOS App卡死問題

### ISSUE THREAD

**Issue by getoutnow2013** [LightNovelShelf/Web#199]
「有新內容可以用了，請刷新或重新打開網頁」
![S__41230338](https://github.com/LightNovelShelf/Web/assets/24822811/e2d5614f-ed66-4954-8054-7f0f3e261758)

這個訊息目前在 iOS APP 上，都是永久卡死，不會自動消失

APP上面也沒有刷新按鈕
之前只能把APP清掉重開來解決

但是本週出BUG後，清APP再重開也沒用
退出登入再登入也沒用，搜尋或看公告什麼的也沒用
就是一直卡死在下方

建議這個訊息，改成可以自動消失
避免遇到本週的BUG時，就永遠卡死在那邊清不掉

**Comment by wuyu8512** [comment]
iOS有没有啥清除网站数据的功能，可以试试
