### ISSUE TITLE
公告页面

### ISSUE THREAD

**Issue by wuyu8512** [LightNovelShelf/Web#22]
已经写好了Api和调用，在两个公告页面将Api实装到页面上，并为两个Api编写TypeScript类型

公告内容为HTML格式，用 `utils/sanitizerHtml` 清理内容，列表页面中公告内容最大显示50字符(字符数量后续可能会改)

**Comment by Azuki-Azusa** [comment]
[分支azu](https://github.com/LightNovelShelf/Web/tree/azu)

**Comment by wuyu8512** [comment]
还可以再改改
比如说getBeforeTime这个函数，其实有一个现成的useToNow可供使用，可以参考BookCard组件
然后announcementList，目前看起来是每次拿到数据就对所有的旧数据也处理了一遍

**Comment by Azuki-Azusa** [comment]
OK

**Comment by wuyu8512** [comment]
突然想起来首页也有公告的信息，之后麻烦补一下，只要显示时间加标题就可，,比如`[2021.12.3] 公告1`
