### ISSUE TITLE
重连的Token刷新问题

### ISSUE THREAD

**Issue by wuyu8512** [LightNovelShelf/Web#23]
目前在ws连接中，中途服务器程序如果突然断开又恢复，这个时候ws在重连，但是这个时候重连没触发token刷新的，等他连上服务器，token其实已经过期处于未授权状态了，然后用户操作了一下调用了api，就会弹出无授权跳到登录页面去了
重连需要刷新token，或者像旧版一样，继续封装token，使30s内token复用，超过30s则刷新

**Comment by Inori-Lover** [comment]
按照当初封装的记录，session token取出来之后把它清掉就好了；
这样下次重连调用 accessTokenFactory 的时候，就拿不到sessionToken然后就回退使用 refreshToken 接口拿token

**Comment by wuyu8512** [comment]
close [commit](https://github.com/LightNovelShelf/Web/commit/4a5ad4e20562122899707903f19a46cc15a83b90)
