### ISSUE TITLE
在公告列表框 靠右放置刷新按钮

### ISSUE THREAD

**Issue by wuyu8512** [LightNovelShelf/Web#26]
像首页的更多那样，在公告列表相同位置，放置刷新图标，点击后重新加载公告

**Comment by Azuki-Azusa** [comment]
好了

**Comment by Inori-Lover** [comment]
> 好了

可以尝试新建一个分支，然后提pr的时候附带一句：

close https://github.com/LightNovelShelf/Web/issues/xx

这样可以在pr通过后就close掉issue
