### ISSUE TITLE
BookInfo加载问题

### ISSUE THREAD

**Issue by wuyu8512** [LightNovelShelf/Web#27]
![image](https://user-images.githubusercontent.com/33444499/146196601-151a16ec-6530-48c2-8f33-b11e2f9f4ec9.png)

先出来了评论，上面是空的，有点问题

**Comment by baka-gourd** [comment]
什么意思？

**Comment by wuyu8512** [comment]
> 什么意思？

你去浏览器录制一下性能就看到了，目前用了pwa，这个问题几乎只是一闪而过

**Comment by baka-gourd** [comment]
新版网页没账号看不了啊😂

**Comment by wuyu8512** [comment]
> 新版网页没账号看不了啊😂

用重制密码功能

**Comment by baka-gourd** [comment]
![image](https://user-images.githubusercontent.com/36119339/147407937-76f20772-76ef-495b-be03-fb788afd6ac7.png)
改了下布局，评论先加载应该是单纯的请求api的时间，评论是写死的

**Comment by wuyu8512** [comment]
你这改动有点大了，我不是很赞同，不过开源的好处就是自己想改啥样就改啥样

**Comment by baka-gourd** [comment]
主要我看的是，现有布局不能在一页里(1920x1080)展示完所有重要信息，而简介下方太空，将目录提前能增加信息密度，还能让整个页面更加对称。
![image](https://user-images.githubusercontent.com/36119339/147408732-6a7fd26c-d10e-42f4-b45d-ee85230e6037.png)
![image](https://user-images.githubusercontent.com/36119339/147408738-fa33fc02-cc6d-4727-abd1-91201d0d62aa.png)
