### ISSUE TITLE
[feature] 更改阅读界面的宽度

### ISSUE THREAD

**Issue by baka-gourd** [LightNovelShelf/Web#32]
目前的阅读界面是100%宽度，对大屏（比如电脑）的阅读宽度极不友好，缩减宽度能够改善阅读体验。
更改后：
![image](https://user-images.githubusercontent.com/36119339/147410107-aa0859aa-d8e9-4eb5-a264-16bbb673e6b2.png)
更改前：
![image](https://user-images.githubusercontent.com/36119339/147410119-7e12ab39-6e25-4718-8101-ccdc114313e3.png)
需要的技术实现：
1. 设置断点，让宽度设置在小屏死不生效或者类似w-11/12，满足小屏需求
2. 大屏下宽度应为一固定值，而不是百分比
3. 我不会用 quasar 的断点，一直都是 tailwind 人
4. 理想情况下，宽度设置保存在用户设置中而不是写死

**Comment by wuyu8512** [comment]
这个确实是有必要的，之后有空我会处理

**Comment by baka-gourd** [comment]
没搞懂这个项目的结构，用quasar却不是quasar项目，quasar很多特性都不能用。然后vue3x最好是ts+class component，这个里的组件的声明也很奇怪。想改完全不知道哪里下手

**Comment by baka-gourd** [comment]
```sass
<style lang="sass">
read
  @media (min-width: $breakpoint-md-min)
    width: 66.6%
</style>
```
这段就是quasar特供的sass，但是不用quasar cli来构建根本不能用

**Comment by wuyu8512** [comment]
`Quasar CLI detects if the file contains at least one ‘$’ character, and if so, it automatically imports the Quasar Sass/SCSS variables.`

官方文档有这样一句，他检测到 `$` 符号就自动导入变量，所以在无cli支持下，只需要手动导入变量，比如
```
@import '/src/styles/quasar.variables.scss';

.read {
  @media (min-width: $breakpoint-md-min) {
    width: 66.6%;
  }
}
```

**Comment by baka-gourd** [comment]
这样确实可以就是，我交个pr看看
