### ISSUE TITLE
网页打开会请求两遍Token

### ISSUE THREAD

**Issue by wuyu8512** [LightNovelShelf/Web#36]
如题

**Comment by baka-gourd** [comment]
我看了下好像不是bug，是在声明hub的时候调用了两次，就算是bug也难修（

**Comment by Inori-Lover** [comment]
> 我看了下好像不是bug，是在声明hub的时候调用了两次，就算是bug也难修（ https://github.com/LightNovelShelf/Web/blob/master/src/services/internal/request/signalr/index.ts#L25-L49

get操作是本地操作

**Comment by Inori-Lover** [comment]
close in https://github.com/LightNovelShelf/Web/blob/56e9841628a1ee21e1c87cc4fef47312a0993197/src/utils/session.ts
