### ISSUE TITLE
设置页面用户体验糟糕

### ISSUE THREAD

**Issue by dandansamax** [LightNovelShelf/Web#50]
* 不同设置项之间的间距太近，比label与对应的input之间的距离还近。
* label和input区域没有明显区分，视觉效果混乱。
* 阅读页宽度选项直接输入像素也太暴力了。。。大部分人连自己的屏幕多大都不知道，改成大中小三个选项会好一点吧。

可以参考一下这种布局
![image](https://user-images.githubusercontent.com/40522713/150648724-f42b9fe2-20af-4884-bb36-243491c53c12.png)

**Comment by wuyu8512** [comment]
1和3可以理解
2直接竖排，其实也是为了照顾不同的屏幕大小
之后我来改进一下

**Comment by baka-gourd** [comment]
> * 不同设置项之间的间距太近，比label与对应的input之间的距离还近。
> * label和input区域没有明显区分，视觉效果混乱。
> * 阅读页宽度选项直接输入像素也太暴力了。。。大部分人连自己的屏幕多大都不知道，改成大中小三个选项会好一点吧。
> 
> 可以参考一下这种布局 ![image](https://user-images.githubusercontent.com/40522713/150648724-f42b9fe2-20af-4884-bb36-243491c53c12.png)

阅读页宽度的问题我整的，本来想用百分比，但是十分明显的结构是在宽的带鱼屏上（甚至16:9）中使用百分比来确定显示宽度都不行，单纯的调整百分比灵活度不行。
当时的解决方案是 9a5c6675224ad4c3dc30d2bd9bc2db3b10ead63e，想要添加一个实时预览提供调节但是后面没整。

**Comment by baka-gourd** [comment]
设置页的问题其实一部分也是页面元素宽度的问题，显得空旷，加点分隔符然后减少宽度可以改善

**Comment by baka-gourd** [comment]
我的建议是直接在设置页和书籍页上套个75%或者60%，撑满真的降低阅读速度

**Comment by dandansamax** [comment]
> 提供大、中、小三种方式归根结底是不能在所有显示器上都拥有良好的体验

大中小也可以使用像素数来决定页面宽度，但是不用给用户直接展示数值。我认为一般情况下没人需要精确到单个像素的细粒度调整。

> 我的建议是直接在设置页和书籍页上套个75%或者60%，撑满真的降低阅读速度

这个我也很认同，现在默认设置体验确实不太好。
