### ISSUE TITLE
反复提示错误问题

### ISSUE THREAD

**Issue by wuyu8512** [LightNovelShelf/Web#55]
如果服务器有返回结果，但结果的success是false，则service会弹出错误
如果业务里try了代码再弹出错误，会出现多次弹出的情况![543dff3c52a31d0d.jpg](https://user-images.githubusercontent.com/33444499/151531120-d8782dc1-6377-45f3-881f-6a92a6f34ff8.jpg)

**Comment by Inori-Lover** [comment]
这个其实有取舍…
要不services弹
要不每个业务自己都弹
再要不就是传一个config做黑/白名单

但最后的方案不好做，因为现在传给requestWithSignalr的参数是个数不定的…没法判断第二个是不是config

**Comment by wuyu8512** [comment]
https://github.com/LightNovelShelf/Web/commit/859755c57a6d0daddb69e85aeb865154cf33fa3c
