### ISSUE TITLE
【feat】全局级别的调用频率限制

### ISSUE THREAD

**Issue by Inori-Lover** [LightNovelShelf/Web#58]
期望实现：
p0:
- [x] 业务层级无需关心频率限制，随意并行触发接口
- [x] 业务无感，接口调用能返回接口调用结果
- [x] 接口调用频率不能超过 10次/5s 

p1:
- [x] 尽可能快地发出，不一定平均时间

**Comment by wuyu8512** [comment]
这个东西，先放一下吧，因为他好像还是不能解决getbookbylist的问题
我另开一个issues
