### ISSUE TITLE
时间处理

### ISSUE THREAD

**Issue by wuyu8512** [LightNovelShelf/Web#6]
在全局store中新增一个time记录当前时间，要求每秒刷新，~~并编写一个计算时间差的工具类函数~~，用在各种时间展示上，比如bookcard中，要求不足一分钟显示刚刚，其余显示x分钟，x小时，x天，x月，x年前

**Comment by Inori-Lover** [comment]
为什么不用库，luxon作为moment的继承者体积缩小功能不变；dayjs用超迷你替换换取月90%的功能，都是不错的选择

**Comment by wuyu8512** [comment]
也好，效果有了我都行

**Comment by Inori-Lover** [comment]
i will handle this

**Comment by Inori-Lover** [comment]
8857bc86184873f2b25f24353e33d80b54ba9452

**Comment by wuyu8512** [comment]
已合
