### ISSUE TITLE
个人信息改动

### ISSUE THREAD

**Issue by wuyu8512** [LightNovelShelf/Web#67]
改动右上角点击头像出来的菜单，实现和b站一样的布局
文字可以写死，之后我来填

**Comment by Soulwail** [comment]
只要一个菜单是吗？还有其他具体要求不

**Comment by wuyu8512** [comment]
> 只要一个菜单是吗？还有其他具体要求不

![image](https://user-images.githubusercontent.com/33444499/153332123-c5451df1-4aee-494c-b421-055a42d19691.png)
这个布局里，除了头像，其他都要
