### ISSUE TITLE
service层新增内容 【缓存请求】以及【速率限制】

### ISSUE THREAD

**Issue by wuyu8512** [LightNovelShelf/Web#7]
- 缓存请求结果 以备无网络时使用

我的想法：离线后的第一个请求始终尝试走服务器，如果第一个请求结束了依旧是离线状态，则后续离线状态下的请求全部直接返回缓存，直到下次上线（在第一个请求的请求期间如果有其他请求，最好能监听一下第一个请求的状态，不能的话就等待吧）

- ~~为请求实现一套令牌桶算法进行速率限制，如果缓存搞定了，超出速率的请求可以直接返回缓存~~

**Comment by wuyu8512** [comment]
另外缓存功能我有个想法，由于现在是websocket，可以得知与服务器的连接情况

假设第一个请求返回了缓存，如何后续的请求到来时，连接状态为离线，那可以直接不等待直接返回缓存，直到下次上线，中途掉线也同理

**Comment by Inori-Lover** [comment]
> 另外缓存功能我有个想法，由于现在是websocket，可以得知与服务器的连接情况
> 
> 假设第一个请求返回了缓存，如果后续的请求到来时，连接状态为离线，那可以不等待直接返回缓存，直到下次上线，中途掉线也同理

这个想法我个人持赞同意见；断线期间可以直接返回缓存，直到重连成功；

但这个需要整体设计，是整体cache-first，还是离线期间cache-first，还是上边的超过限制就cache-only；整体设计要有一条路线，全都上的话代码带来的价值就没那么高了

**Comment by wuyu8512** [comment]
~~象征性的搞一个避免大量请求~~，服务端技术上问题很难搞，所以想着要么就客户端搞，不过确实暂时没啥用，我更新一下需求，先把缓存搞了吧

**Comment by Inori-Lover** [comment]
dev/inori/cache-for-signalr

实现对signalr的cache了；

理想状态下底层应该仅有一套services所以目前只实现它也没理应够用

**Comment by wuyu8512** [comment]
我看了一下预览地址: https://531be509.web-9q6.pages.dev/
第一次进入成功连接服务器并请求
第二次必读无法连接，清空db后重复
