### ISSUE TITLE
profile 页面优化

### ISSUE THREAD

**Issue by baka-gourd** [LightNovelShelf/Web#97]
做的人在dark模式下看过吗:thinking:

**Comment by wuyu8512** [comment]
草，这我还真忘记看了，不过这个也简单，等一个有缘人pr了

**Comment by baka-gourd** [comment]
进组有什么要求嘛，我是Vue、C#都会一点

**Comment by wuyu8512** [comment]
> 进组有什么要求嘛，我是Vue、C#都会一点

你在本仓库的代码量还不够
